package com.lodygames.rpgquest.panel.web;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.lodygames.rpgquest.panel.agent.AgentStore;
import com.lodygames.rpgquest.panel.audit.InMemoryAuditLog;
import com.lodygames.rpgquest.panel.bridge.BridgeClient;
import com.lodygames.rpgquest.panel.support.TestConfig;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.time.Duration;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Rendu de la page {@code /travel} (issue #152) : consultation lecture seule des waypoints/bornes
 * persistés, via l'action agent {@code travel.catalog} déjà exercée côté plugin.
 */
class TravelCatalogTest {

    @TempDir
    Path tmp;

    private PanelApp app;
    private int port;
    private HttpClient client;
    private final Map<String, String> jar = new LinkedHashMap<>();

    // Un waypoint Hub apparié (foret_du_hub), un waypoint Hub sans borne (clairiere_perdue),
    // une borne auto-générée appariée et une borne administrée (non auto) sans waypoint lié.
    private static final String TRAVEL_DETAILS = "{"
            + "\"waypointCount\":2,\"beaconCount\":2,\"autoGeneratedBeaconCount\":1,"
            + "\"unpairedHubWaypointIds\":[\"clairiere_perdue\"],\"generatedAtEpochMs\":" + System.currentTimeMillis() + ","
            + "\"waypoints\":["
            + "{\"id\":\"foret_du_hub\",\"displayName\":\"Forêt du Hub\",\"world\":\"hub\",\"biomeKey\":\"FOREST\","
            + "\"biomeInstance\":\"0,0\",\"x\":12,\"y\":64,\"z\":-8,\"active\":true,\"modelVersion\":1,\"beaconPaired\":true},"
            + "{\"id\":\"clairiere_perdue\",\"displayName\":\"Clairière perdue\",\"world\":\"hub\",\"biomeKey\":\"PLAINS\","
            + "\"biomeInstance\":\"1,0\",\"x\":150,\"y\":70,\"z\":30,\"active\":true,\"modelVersion\":1,\"beaconPaired\":false}"
            + "],"
            + "\"beacons\":["
            + "{\"id\":\"beacon-1\",\"world\":\"hub\",\"x\":12,\"y\":64,\"z\":-8,\"active\":true,\"modelVersion\":1,"
            + "\"autoGenerated\":true,\"biomeInstance\":\"0,0\",\"pairedWaypointId\":\"foret_du_hub\"},"
            + "{\"id\":\"beacon-admin-1\",\"world\":\"wild\",\"x\":400,\"y\":80,\"z\":400,\"active\":true,\"modelVersion\":1,"
            + "\"autoGenerated\":false,\"biomeInstance\":null,\"pairedWaypointId\":null}"
            + "]}";

    @AfterEach
    void tearDown() {
        if (app != null) {
            app.stop();
        }
    }

    @Test
    void emptyStateBeforeFirstRefresh() throws Exception {
        start();
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();
        assertTrue(page.contains("Aucun catalogue chargé"), "invite à rafraîchir tant qu'aucun relevé n'existe");
        assertTrue(page.contains("name=\"type\" value=\"travel.catalog\""), "bouton Rafraîchir déclenche travel.catalog");
    }

    @Test
    void listsWaypointsAndBeaconsWithPairingAndFreshness() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();

        assertTrue(page.contains("2 waypoint(s)") && page.contains("2 borne(s)") && page.contains("1 auto-générée(s)"),
                "synthèse des compteurs");
        assertTrue(page.contains("1 waypoint(s) du Hub sans borne appariée"), "compteur des waypoints non appariés");
        assertTrue(page.contains("Donnée relevée il y a"), "horodatage de fraîcheur affiché");

        assertTrue(page.contains("<code>foret_du_hub</code>") && page.contains("Forêt du Hub"), "waypoint apparié listé");
        assertTrue(page.contains("<code>clairiere_perdue</code>") && page.contains("Clairière perdue"),
                "waypoint non apparié listé");
        assertTrue(page.contains("<code>beacon-1</code>"), "borne auto listée");
        assertTrue(page.contains("<code>beacon-admin-1</code>"), "borne administrée listée");

        // badges de pairage : une borne auto-générée appariée, un waypoint sans borne en warning
        assertTrue(page.contains("badge text-bg-success\">oui</span>"), "waypoint apparié marqué oui");
        assertTrue(page.contains("badge text-bg-warning\">non</span>"), "waypoint non apparié marqué non");
        assertTrue(page.contains("badge text-bg-info\">auto (Hub)</span>"), "borne auto-générée identifiée");
        assertTrue(page.contains("badge text-bg-secondary\">administrée</span>"), "borne administrée identifiée");
        assertTrue(page.contains("<code>foret_du_hub</code>") , "waypoint apparié référencé depuis la table des bornes");

        // distinction explicite "enregistré" vs "vérifié physiquement" demandée par le ticket
        // (apostrophe HTML-échappée par Http.esc dans le sous-titre, voir Ui#pageHeader)
        assertTrue(page.contains("pas une confirmation qu&#39;elle") && page.contains("physiquement présente"),
                "avertissement explicite enregistré != vérifié");
    }

    @Test
    void searchFiltersAcrossIdNameAndBiome() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID + "&q=clairiere").body();

        assertTrue(page.contains("clairiere_perdue"), "le waypoint recherché reste visible");
        assertFalse(page.contains("foret_du_hub"), "le waypoint non filtré est exclu de la recherche");
    }

    @Test
    void worldFilterScopesBothTables() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID + "&world=wild").body();

        assertTrue(page.contains("beacon-admin-1"), "la borne du monde wild reste visible");
        assertFalse(page.contains("foret_du_hub"), "le waypoint du hub est exclu par le filtre monde");
        assertFalse(page.contains("<code>beacon-1</code>"), "la borne du hub est exclue par le filtre monde");
    }

    @Test
    void readOnlyRoleCannotMutateButCanRefreshCatalog() throws Exception {
        start();
        // READ_ONLY a bien TRAVEL_READ (voir Role.READ_ONLY) : la page et le rafraîchissement
        // (non-mutant, voir AgentActionCatalog#"travel.catalog") doivent rester accessibles.
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();
        assertTrue(page.contains("Réseau de voyage"), "page accessible à l'OWNER (et par extension aux rôles avec TRAVEL_READ)");
        assertFalse(page.contains(">Modifier</button>"), "aucun éditeur : consultation lecture seule uniquement (#152)");
    }

    // ---- helpers ----------------------------------------------------------------------

    private void runCatalogWithSuccess(String details) throws Exception {
        String token = csrf(get("/travel?agent=" + TestConfig.AGENT_ID).body());
        post("/agents/action", "_csrf=" + token + "&type=travel.catalog&agent=" + TestConfig.AGENT_ID + "&return=/travel");
        HttpResponse<String> poll = client.send(HttpRequest.newBuilder(uri("/agent/v1/actions"))
                .header("Authorization", "Bearer " + TestConfig.AGENT_TOKEN)
                .header("X-Agent-Id", TestConfig.AGENT_ID).GET().build(), HttpResponse.BodyHandlers.ofString());
        Matcher m = Pattern.compile("\"id\"\\s*:\\s*\"([0-9a-f-]{36})\"").matcher(poll.body());
        m.find();
        String id = m.group(1);
        String result = "{\"action_id\":\"" + id + "\",\"status\":\"SUCCESS\",\"value\":\"4\","
                + "\"message\":\"2 waypoints, 2 bornes\",\"details\":" + details + "}";
        client.send(HttpRequest.newBuilder(uri("/agent/v1/actions/" + id + "/result"))
                .header("Authorization", "Bearer " + TestConfig.AGENT_TOKEN)
                .header("X-Agent-Id", TestConfig.AGENT_ID)
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(result)).build(), HttpResponse.BodyHandlers.ofString());
    }

    private void start() throws Exception {
        String db = tmp.resolve("cp.db").toString();
        app = new PanelApp(TestConfig.withAgent(db, "http://127.0.0.1:1/admin/v1"),
                new InMemoryAuditLog(), new BridgeClient(Duration.ofMillis(300), Duration.ofMillis(400)),
                new AgentStore(db));
        port = app.start();
        client = HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NEVER).build();
        jar.clear();
        String token = csrf(get("/login").body());
        post("/login", "username=" + TestConfig.OWNER_USERNAME + "&password="
                + URLEncoder.encode(TestConfig.OWNER_PASSWORD, StandardCharsets.UTF_8) + "&_csrf=" + token);
    }

    private static String csrf(String html) {
        Matcher m = Pattern.compile("name=\"_csrf\" value=\"([^\"]+)\"").matcher(html);
        m.find();
        return m.group(1);
    }

    private HttpResponse<String> get(String p) throws Exception {
        return send(HttpRequest.newBuilder(uri(p)).GET());
    }

    private HttpResponse<String> post(String p, String form) throws Exception {
        return send(HttpRequest.newBuilder(uri(p))
                .header("Content-Type", "application/x-www-form-urlencoded")
                .POST(HttpRequest.BodyPublishers.ofString(form)));
    }

    private URI uri(String p) {
        return URI.create("http://127.0.0.1:" + port + p);
    }

    private HttpResponse<String> send(HttpRequest.Builder b) throws Exception {
        if (!jar.isEmpty()) {
            b.header("Cookie", jar.entrySet().stream()
                    .map(e -> e.getKey() + "=" + e.getValue()).reduce((x, y) -> x + "; " + y).orElse(""));
        }
        HttpResponse<String> res = client.send(b.build(), HttpResponse.BodyHandlers.ofString());
        for (String sc : res.headers().allValues("Set-Cookie")) {
            String[] f = sc.split(";", 2);
            int eq = f[0].indexOf('=');
            String n = f[0].substring(0, eq).trim();
            String v = f[0].substring(eq + 1).trim();
            if (sc.toLowerCase().contains("max-age=0") || v.isEmpty()) {
                jar.remove(n);
            } else {
                jar.put(n, v);
            }
        }
        return res;
    }
}
