package com.lodygames.rpgquest.panel.web;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.lodygames.rpgquest.panel.agent.AgentStore;
import com.lodygames.rpgquest.panel.audit.InMemoryAuditLog;
import com.lodygames.rpgquest.panel.bridge.BridgeClient;
import com.lodygames.rpgquest.panel.support.TestConfig;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.time.Duration;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Rendu de la page {@code /travel} (issue #152) : consultation lecture seule des waypoints/bornes
 * persistés, via l'action agent {@code travel.catalog} déjà exercée côté plugin.
 */
class TravelCatalogTest {

    @TempDir
    Path tmp;

    private PanelApp app;
    private int port;
    private HttpClient client;
    private final Map<String, String> jar = new LinkedHashMap<>();

    // Un waypoint Hub apparié (foret_du_hub), un waypoint Hub sans borne (clairiere_perdue),
    // une borne auto-générée appariée et une borne administrée (non auto) sans waypoint lié.
    private static final String TRAVEL_DETAILS = "{"
            // Issue #156 : le référentiel du réseau (monde Hub, spawn, seuils réels) et le réseau du
            // Wild, sans lesquels la page devrait supposer ce qu'elle affiche.
            + "\"hubWorld\":\"hub\",\"hubSpawnX\":0,\"hubSpawnZ\":0,\"hubSpawnKnown\":true,"
            + "\"instanceRegionSize\":512,\"beaconPairMinSpacing\":6,\"beaconPairMaxSpacing\":16,"
            + "\"waypointMinimumSpacing\":64,\"hubBeaconGenerationEnabled\":true,"
            + "\"waystoneNetworks\":[{\"world\":\"wild\",\"total\":7,\"discovered\":0,\"cellSize\":1000,"
            + "\"chance\":0.6,\"minimumSpacing\":96,\"minX\":-1000,\"maxX\":1000,\"minZ\":-500,\"maxZ\":500}],"
            + "\"waypointCount\":2,\"beaconCount\":2,\"autoGeneratedBeaconCount\":1,"
            + "\"unpairedHubInstances\":[{\"waypointId\":\"clairiere_perdue\",\"biomeInstance\":\"1,0\","
            + "\"biomeKey\":\"PLAINS\",\"x\":150,\"z\":30,\"attempts\":0,\"nextRetryEpochMs\":null,"
            + "\"inProgress\":false,\"nearestBeaconDistance\":96}],"
            + "\"generatedAtEpochMs\":" + System.currentTimeMillis() + ","
            + "\"waypoints\":["
            + "{\"id\":\"foret_du_hub\",\"displayName\":\"Forêt du Hub\",\"world\":\"hub\",\"biomeKey\":\"FOREST\","
            + "\"biomeInstance\":\"0,0\",\"x\":12,\"y\":64,\"z\":-8,\"active\":true,\"modelVersion\":1,\"pairedBeaconId\":\"beacon-1\",\"createdAt\":\"2026-01-01T10:00:00Z\"},"
            + "{\"id\":\"clairiere_perdue\",\"displayName\":\"Clairière perdue\",\"world\":\"hub\",\"biomeKey\":\"PLAINS\","
            + "\"biomeInstance\":\"1,0\",\"x\":150,\"y\":70,\"z\":30,\"active\":true,\"modelVersion\":1,\"pairedBeaconId\":null,\"createdAt\":\"2026-01-02T10:00:00Z\"}"
            + "],"
            + "\"beacons\":["
            + "{\"id\":\"beacon-1\",\"world\":\"hub\",\"x\":12,\"y\":64,\"z\":-8,\"active\":true,\"modelVersion\":1,"
            + "\"autoGenerated\":true,\"biomeInstance\":\"0,0\",\"pairedWaypointId\":\"foret_du_hub\",\"createdAt\":\"2026-01-01T10:00:17Z\"},"
            + "{\"id\":\"beacon-admin-1\",\"world\":\"wild\",\"x\":400,\"y\":80,\"z\":400,\"active\":true,\"modelVersion\":1,"
            + "\"autoGenerated\":false,\"biomeInstance\":null,\"pairedWaypointId\":null,\"createdAt\":\"2026-01-03T10:00:00Z\"}"
            + "]}";

    @AfterEach
    void tearDown() {
        if (app != null) {
            app.stop();
        }
    }

    @Test
    void emptyStateBeforeFirstRefresh() throws Exception {
        start();
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();
        assertTrue(page.contains("Aucun catalogue chargé"), "invite à rafraîchir tant qu'aucun relevé n'existe");
        assertTrue(page.contains("name=\"type\" value=\"travel.catalog\""), "bouton Rafraîchir déclenche travel.catalog");
    }

    @Test
    void listsWaypointsAndBeaconsWithPairingAndFreshness() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();

        assertTrue(page.contains("2 waypoint(s)") && page.contains("2 borne(s)") && page.contains("1 auto-générée(s)"),
                "synthèse des compteurs");
        assertTrue(page.contains("1 waypoint(s) du Hub sans borne appariée"), "compteur des waypoints non appariés");
        assertTrue(page.contains("Donnée relevée il y a"), "horodatage de fraîcheur affiché");

        assertTrue(page.contains("<code>foret_du_hub</code>") && page.contains("Forêt du Hub"), "waypoint apparié listé");
        assertTrue(page.contains("<code>clairiere_perdue</code>") && page.contains("Clairière perdue"),
                "waypoint non apparié listé");
        assertTrue(page.contains("<code>beacon-1</code>"), "borne auto listée");
        assertTrue(page.contains("<code>beacon-admin-1</code>"), "borne administrée listée");

        // Retour joueur 2026-10-04 : « Apparié » (oui/non) remplacé par « Borne associée »
        // affichant directement l'id de la borne associée, jamais un simple booléen.
        assertTrue(page.contains("Borne associée") && page.contains("Waypoint associé"),
                "libellés explicites, plus de « Apparié » ambigu");
        assertTrue(page.contains("<code>beacon-1</code>"), "l'id de la borne associée doit apparaître dans la table des waypoints");
        assertTrue(page.contains("badge text-bg-warning\">aucune</span>"), "waypoint non associé marqué explicitement");
        assertTrue(page.contains("badge text-bg-info\">auto (Hub)</span>"), "borne auto-générée identifiée");
        assertTrue(page.contains("badge text-bg-secondary\">administrée</span>"), "borne administrée identifiée");
        assertTrue(page.contains("<code>foret_du_hub</code>") , "waypoint associé référencé depuis la table des bornes");
        assertTrue(page.contains("badge text-bg-warning\">aucun</span>"), "borne sans waypoint associé marquée explicitement");

        // distinction explicite "enregistré" vs "vérifié physiquement" demandée par le ticket
        // (apostrophe HTML-échappée par Http.esc dans le sous-titre, voir Ui#pageHeader)
        assertTrue(page.contains("pas une confirmation qu&#39;elle") && page.contains("physiquement présente"),
                "avertissement explicite enregistré != vérifié");
    }

    /**
     * Issue #156 — la page doit dire <em>pourquoi</em> une instance Hub n'a pas de borne. Constater le
     * manque ne permettait pas de distinguer un déclencheur en défaut d'un refus de terrain.
     */
    @Test
    void unpairedHubInstancesExposeTheirPairingCause() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();

        assertTrue(page.contains("Appariements manquants dans le Hub (1)"), "section dédiée avec son compteur");
        assertTrue(page.contains("badge text-bg-secondary\">jamais tenté</span>"),
                "0 essai = appariement jamais tenté, pas un refus de terrain");
        assertTrue(page.contains("96 blocs"), "distance à la borne la plus proche, pour juger de l'espacement");
        assertTrue(page.contains("un redémarrage du serveur"), "les compteurs en mémoire doivent être annoncés comme tels");
    }

    /** Issue #156 — aucun manque : la page le dit, elle n'affiche pas une table vide. */
    @Test
    void anEntirelyPairedHubIsStatedExplicitly() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS.replaceFirst(
                "\"unpairedHubInstances\":\\[\\{[^]]*}]", "\"unpairedHubInstances\":[]"));
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();

        assertTrue(page.contains("Appariements manquants dans le Hub (0)"), "section présente même sans manque");
        assertTrue(page.contains("a sa borne"), "état sain énoncé explicitement");
    }

    // ---- Diagnostic réseau (issue #156) --------------------------------------------------------

    /**
     * La question d'origine — « pourquoi seulement 13 bornes ? » — doit trouver sa réponse sur
     * l'écran, et pas dans un rapport : les bornes n'existent que dans le Hub, et leur nombre mesure
     * l'exploration réelle, pas une densité configurée.
     */
    @Test
    void theHubDiagnosticStatesThePolicyAndTheTriggerBeforeAnyList() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();

        assertTrue(page.contains("Réseau Hub — diagnostic"), "section de diagnostic présente");
        assertTrue(page.contains("uniquement</strong> dans "), "la politique « Hub seulement » est énoncée");
        assertTrue(page.contains("mesure "), "le nombre de bornes est présenté comme une mesure");
        assertTrue(page.contains("l'exploration réelle du Hub</strong>"),
                "le déclencheur réel (l'exploration) est nommé, pas supposé");
        assertTrue(page.contains("aucun balayage du monde"), "l'absence de balayage est dite explicitement");
        assertTrue(page.contains("instances du Hub (waypoints)") && page.contains("paires complètes")
                        && page.contains("instances sans borne") && page.contains("bornes orphelines"),
                "les quatre chiffres du diagnostic sont affichés séparément");
        // 2 waypoints Hub, 1 borne auto appariée, 1 manque, 0 orpheline.
        assertTrue(page.contains("512 blocs)"), "la taille d'instance réelle est citée, jamais devinée");
        assertTrue(page.contains("entre 6"), "l'anneau d'appariement réellement configuré est cité");
    }

    /** La couverture : sans elle, « peu de bornes » ne peut pas être confronté à « sur quelle étendue ». */
    @Test
    void theCoverageSectionGivesDistancesAndSaysWhenTheyAreNotComputable() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();

        assertTrue(page.contains("Couverture du Hub"), "section de couverture présente");
        assertTrue(page.contains("Distance à la borne la plus proche"), "distance entre bornes mesurée");
        // Une seule borne dans le Hub : il n'existe aucune distance entre bornes.
        assertTrue(page.contains("non calculable (moins de deux points)"),
                "avec une borne seule, la page doit le dire plutôt qu'afficher zéro");
        assertTrue(page.contains("Distance au spawn du Hub"), "distance au spawn mesurée");
        assertTrue(page.contains("Étendue couverte"), "étendue X/Z affichée");
    }

    /** §8 du ticket : chaque borne devient une fiche ouvrable, sans JavaScript. */
    @Test
    void eachHubBeaconBecomesAnOpenableSheet() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();

        assertTrue(page.contains("Bornes du Hub — fiche par borne (1)"), "section et compteur");
        assertTrue(page.contains("<details"), "fiche ouvrable en HTML natif (la CSP interdit le script en ligne)");
        assertTrue(page.contains("Instance servie"), "la fiche dit quelle instance la borne équipe");
        assertTrue(page.contains("Distance à son waypoint"), "la distance au waypoint est confrontée à l'anneau");
        assertTrue(page.contains("auto-générée par l'exploration"), "l'origine de la borne est explicite");
        assertFalse(page.contains("beacon-admin-1</code> — "),
                "la borne du Wild n'a pas de fiche : elle n'appartient pas au réseau du Hub");
    }

    /** §9 du ticket : les instances connues du Hub, avec leur état et leur cause. */
    @Test
    void knownHubInstancesAreListedWithTheirStateAndCause() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();

        assertTrue(page.contains("Instances connues du Hub (2)"), "les deux instances du Hub sont listées");
        assertTrue(page.contains("badge text-bg-success\">borne présente</span>"), "instance équipée");
        assertTrue(page.contains("badge text-bg-warning\">sans borne</span>"), "instance en manque");
        assertTrue(page.contains("jamais tenté"), "la cause du manque est affichée dans la fiche");
        assertTrue(page.contains("pas un manque, elle n'est pas encore découverte")
                        || page.contains("elle n&#39;est pas encore découverte"),
                "une instance jamais traversée ne doit pas être comptée comme un manque");
    }

    /**
     * Le rattrapage autorisé par le ticket : une instance désignée, un essai. Le texte doit dire sa
     * portée — c'est précisément ce qu'un bouton « Réparer » laisserait deviner.
     */
    @Test
    void aTargetedPairingIsOfferedForAMissingInstanceAndStatesItsExactScope() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();

        assertTrue(page.contains("name=\"type\" value=\"travel.beacon.pair\""), "action ciblée proposée");
        assertTrue(page.contains("name=\"waypointId\" value=\"clairiere_perdue\""),
                "l'instance visée est désignée par SON waypoint, jamais par des coordonnées libres");
        assertTrue(page.contains("name=\"confirm\""), "mutation sensible : confirmation explicite");
        assertTrue(page.contains("cette instance "), "la portée du geste est écrite");
        assertTrue(page.contains("aucune densité "), "l'absence de changement d'équilibrage est dite");
        assertFalse(page.contains("value=\"foret_du_hub\"></div>"),
                "aucun appariement proposé pour une instance déjà équipée");
    }

    /** La confusion à empêcher : chercher des bornes dans le Wild ne donnera jamais rien. */
    @Test
    void theWildSectionSaysItHasNoBeaconsAndCountsDiscoveredWaystones() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();

        assertTrue(page.contains("Réseau du Wild — Waystones"), "le réseau du Wild est présenté à part");
        assertTrue(page.contains("aucune</strong> borne"), "l'absence de borne dans le Wild est énoncée");
        assertTrue(page.contains("7 Waystone(s)") && page.contains("0 découverte(s)"),
                "existence et découverte sont deux chiffres distincts");
        assertTrue(page.contains("n'a jamais été découverte") || page.contains("n&#39;a jamais été découverte"),
                "zéro découverte doit être signalé : le réseau est inexistant pour les joueurs");
        assertTrue(page.contains("60 %"), "la probabilité réelle de la grille est citée");
    }

    /**
     * Le panel se déploie **avant** le plugin : pendant quelques minutes, le dernier relevé vient
     * d'une version qui n'envoyait pas le référentiel du réseau. L'écran doit le dire, et surtout
     * pas affirmer qu'aucun monde Hub n'est configuré.
     */
    @Test
    void aReadingFromAnOlderPluginAsksForARefreshInsteadOfClaimingNoHub() throws Exception {
        start();
        runCatalogWithSuccess("{\"waypointCount\":0,\"beaconCount\":0,\"autoGeneratedBeaconCount\":0,"
                + "\"unpairedHubInstances\":[],\"waypoints\":[],\"beacons\":[],"
                + "\"generatedAtEpochMs\":" + System.currentTimeMillis() + "}");
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();

        assertTrue(page.contains("Réseau Hub — diagnostic"), "la section reste présente");
        assertTrue(page.contains("version du plugin antérieure"), "la vraie raison est donnée");
        assertFalse(page.contains("Aucun monde Hub configuré"),
                "surtout pas une affirmation fausse sur la configuration du serveur");
        assertFalse(page.contains("Couverture du Hub"), "aucune statistique sur un relevé incomplet");
    }

    /** Une moyenne calculée sur un sous-ensemble filtré serait présentée comme la couverture du réseau. */
    @Test
    void aFilterHidesTheDiagnosticRatherThanAveragingASubset() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID + "&world=hub").body();

        assertFalse(page.contains("Couverture du Hub"), "aucune statistique sur un sous-ensemble");
        assertTrue(page.contains("Filtre actif"), "la raison du masquage est dite");
    }

    @Test
    void searchFiltersAcrossIdNameAndBiome() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID + "&q=clairiere").body();

        assertTrue(page.contains("clairiere_perdue"), "le waypoint recherché reste visible");
        assertFalse(page.contains("foret_du_hub"), "le waypoint non filtré est exclu de la recherche");
    }

    @Test
    void worldFilterScopesBothTables() throws Exception {
        start();
        runCatalogWithSuccess(TRAVEL_DETAILS);
        String page = get("/travel?agent=" + TestConfig.AGENT_ID + "&world=wild").body();

        assertTrue(page.contains("beacon-admin-1"), "la borne du monde wild reste visible");
        assertFalse(page.contains("foret_du_hub"), "le waypoint du hub est exclu par le filtre monde");
        assertFalse(page.contains("<code>beacon-1</code>"), "la borne du hub est exclue par le filtre monde");
    }

    @Test
    void readOnlyRoleCannotMutateButCanRefreshCatalog() throws Exception {
        start();
        // READ_ONLY a bien TRAVEL_READ (voir Role.READ_ONLY) : la page et le rafraîchissement
        // (non-mutant, voir AgentActionCatalog#"travel.catalog") doivent rester accessibles.
        String page = get("/travel?agent=" + TestConfig.AGENT_ID).body();
        assertTrue(page.contains("Réseau de voyage"), "page accessible à l'OWNER (et par extension aux rôles avec TRAVEL_READ)");
        assertFalse(page.contains(">Modifier</button>"), "aucun éditeur : consultation lecture seule uniquement (#152)");
    }

    // ---- helpers ----------------------------------------------------------------------

    private void runCatalogWithSuccess(String details) throws Exception {
        String token = csrf(get("/travel?agent=" + TestConfig.AGENT_ID).body());
        post("/agents/action", "_csrf=" + token + "&type=travel.catalog&agent=" + TestConfig.AGENT_ID + "&return=/travel");
        HttpResponse<String> poll = client.send(HttpRequest.newBuilder(uri("/agent/v1/actions"))
                .header("Authorization", "Bearer " + TestConfig.AGENT_TOKEN)
                .header("X-Agent-Id", TestConfig.AGENT_ID).GET().build(), HttpResponse.BodyHandlers.ofString());
        Matcher m = Pattern.compile("\"id\"\\s*:\\s*\"([0-9a-f-]{36})\"").matcher(poll.body());
        m.find();
        String id = m.group(1);
        String result = "{\"action_id\":\"" + id + "\",\"status\":\"SUCCESS\",\"value\":\"4\","
                + "\"message\":\"2 waypoints, 2 bornes\",\"details\":" + details + "}";
        client.send(HttpRequest.newBuilder(uri("/agent/v1/actions/" + id + "/result"))
                .header("Authorization", "Bearer " + TestConfig.AGENT_TOKEN)
                .header("X-Agent-Id", TestConfig.AGENT_ID)
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(result)).build(), HttpResponse.BodyHandlers.ofString());
    }

    private void start() throws Exception {
        String db = tmp.resolve("cp.db").toString();
        app = new PanelApp(TestConfig.withAgent(db, "http://127.0.0.1:1/admin/v1"),
                new InMemoryAuditLog(), new BridgeClient(Duration.ofMillis(300), Duration.ofMillis(400)),
                new AgentStore(db));
        port = app.start();
        client = HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NEVER).build();
        jar.clear();
        String token = csrf(get("/login").body());
        post("/login", "username=" + TestConfig.OWNER_USERNAME + "&password="
                + URLEncoder.encode(TestConfig.OWNER_PASSWORD, StandardCharsets.UTF_8) + "&_csrf=" + token);
    }

    private static String csrf(String html) {
        Matcher m = Pattern.compile("name=\"_csrf\" value=\"([^\"]+)\"").matcher(html);
        m.find();
        return m.group(1);
    }

    private HttpResponse<String> get(String p) throws Exception {
        return send(HttpRequest.newBuilder(uri(p)).GET());
    }

    private HttpResponse<String> post(String p, String form) throws Exception {
        return send(HttpRequest.newBuilder(uri(p))
                .header("Content-Type", "application/x-www-form-urlencoded")
                .POST(HttpRequest.BodyPublishers.ofString(form)));
    }

    private URI uri(String p) {
        return URI.create("http://127.0.0.1:" + port + p);
    }

    private HttpResponse<String> send(HttpRequest.Builder b) throws Exception {
        if (!jar.isEmpty()) {
            b.header("Cookie", jar.entrySet().stream()
                    .map(e -> e.getKey() + "=" + e.getValue()).reduce((x, y) -> x + "; " + y).orElse(""));
        }
        HttpResponse<String> res = client.send(b.build(), HttpResponse.BodyHandlers.ofString());
        for (String sc : res.headers().allValues("Set-Cookie")) {
            String[] f = sc.split(";", 2);
            int eq = f[0].indexOf('=');
            String n = f[0].substring(0, eq).trim();
            String v = f[0].substring(eq + 1).trim();
            if (sc.toLowerCase().contains("max-age=0") || v.isEmpty()) {
                jar.remove(n);
            } else {
                jar.put(n, v);
            }
        }
        return res;
    }
}
