name: RPGQuest
version: ${version}
main: be.lloyd.rpgquest.RPGQuestPlugin
api-version: '1.21'
author: Lloyd
description: Plugin RPG pour Paper piloté par des quêtes YAML.
folia-supported: false

commands:
  rpgquest:
    description: Commande principale de RPGQuest.
    usage: /<command> <version|help>
