package com.lodygames.rpgquest.travel.beacon.model;

import java.time.Instant;

/**
 * Une borne de téléportation physique (issues #132/#150/#149) : support identique à un waypoint
 * (`waypoint.render.WaypointModelV1`), mais bloc de diamant au lieu du bloc d'or et bouton en bois
 * au lieu du bouton en pierre. Son bouton ouvre le menu de voyage ; il ne découvre jamais le
 * waypoint voisin et n'est jamais fusionné avec l'identité/table des waypoints ou des waystones
 * (systèmes distincts, voir {@code waypoint.model.Waypoint} / {@code waystone.model.Waystone}).
 *
 * <p>{@code id} : identifiant technique stable, dérivé de la position d'ancre (placement
 * administré, {@code beacon_<world>_<x>_<y>_<z>}) ou de l'instance de biome appariée (génération
 * automatique du Hub, issue #149, {@code beacon_auto_<world>_<biome>_<regionX>_<regionZ>}) —
 * jamais du rendu. {@code x}/{@code y}/{@code z} : ancre (colonne de surface), pas l'interacteur.
 * {@code facing} : orientation cardinale de l'interacteur. {@code active} : borne désactivée =
 * bouton inerte. {@code biomeInstance} : {@code ""} pour une borne placée à la main (#132, jamais
 * liée à une instance précise) ; sinon {@code BiomeInstanceKey#serialize()} de l'instance de biome
 * du Hub à laquelle cette borne est appariée (issue #149) — sert uniquement à l'idempotence de
 * l'appariement, jamais une fusion avec la table {@code waypoints}.</p>
 */
public record TravelBeacon(String id, String world, int x, int y, int z, String facing,
                            int modelVersion, boolean active, String biomeInstance, Instant createdAt) {

    public TravelBeacon {
        biomeInstance = biomeInstance == null ? "" : biomeInstance;
    }

    /** Vrai si cette borne a été générée automatiquement pour une instance de biome (issue #149), jamais placée à la main. */
    public boolean isAutoGenerated() {
        return !biomeInstance.isBlank();
    }
}
